# mr. morden quotes from babylon 5

quotes = [
 "All I can tell you is we have what we want."
,"The rest is no concern to us."
,"And based on your promise to take care of it, they accept your responsibility without question or hesitation."
,"And how is your war going?"
,"And then what?"
,"Anything I can do to help?"
,"As you say."
,"Beyond a shadow of a doubt."
,"Destiny is on our side."
,"Does that invalidate the question?"
,"Good. My associates will be very happy to hear that."
,"How can I be of service?"
,"I believe that this little demonstration will bring you some very interesting propositions."
,"I have to meet with my associates, but let's say we reconvene later to discuss it."
,"I hear you've been looking for me."
,"I see."
# ,"I thought we had a deal."
,"I trust it is still safe."
,"I understand you were looking for me."
,"I was authorized to speak to you."
,"I was just on my way to see you."
,"I'll be around."
,"I'm here to be of service."
,"I'm leaving shortly. I got what I came for." 
,"Before I go... A gift from friends you don't know you have."
,"I'm not allowed to leave you until you've answered my question."
,"In the future, if we deliver on our promises, we may come to you and ask you for a favor."
,"Interesting. What exactly did you have in mind?"
,"Is that why you called me here?"
,"Just making conversation."
,"My associates believe you're a person of great potential trapped in a position where you're unappreciated. They'd like to change that."
,"My associates need a voice and an ear."
,"No price."
,"Of course. As ever, I am always in your service."
,"One last thing. A small favor in return for our good efforts on your behalf. "
,"A person in an important position like yours hears many things."
,"If you should hear about anything strange, I'd appreciate being informed. Even if it seems unimportant."
,"One small exception hardly worth mentioning..."
,"One thing at a time."
,"Perfect symmetry."
,"Perhaps."
,"Something wrong?"
,"Tell them you will personally take care of it."
,"That's what I was going to ask you."
,"The power is now yours."
,"The question is its own purpose."
,"The rest is yours. Good day."
,"Then we'll provide it."
,"Simply choose your target."
,"There's no need to rush things."
,"They can dismiss this as an isolated incident."
,"I'm here to be of service."
,"We have a vested interest in it."
,"We're simply here to help."
,"What do you want?"
,"When the time is right."
,"Yes, I think he's ready."
,"Perfect for our needs."
,"No, he suspects nothing."
,"Yes, well, that's to be expected."
,"Yes. That was the intent."
,"My associates and I are doing everything we can to help."
,"I should think you'd be grateful."
,"You have a problem. I believe I can help."
,"You have a problem. I can help."
,"You have a problem. We can fix it, if you let us."
,"You wanted to see me?"
]
